name: Manual workflow

on: 
  workflow_dispatch:
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.11"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install --upgrade robotframework-seleniumlibrary
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.2.0
      - name: Test with robot framework
        run: |
          robot browser.robot
     
